apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana-ksa
  namespace: default
  annotations:
    iam.gke.io/gcp-service-account: grafana-monitoring-reader@project-81c35834-dcf8-4001-9b2.iam.gserviceaccount.com