serviceAccount:
  create: false
  name: grafana-ksa

rbac:
  create: false
  
service:
  type: LoadBalancer
  loadBalancerSourceRanges:
    - "0.0.0.0/0"
adminUser: admin

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 250m
    memory: 512Mi

persistence:
  enabled: true
  size: 1Gi

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      # Section A + B
      - name: Google Cloud Monitoring
        uid: google-cloud-monitoring
        type: stackdriver
        access: proxy
        isDefault: true
        editable: true
        jsonData:
          authenticationType: gce
          defaultProject: ${PROJECT_ID}

      # Section C + D
      - name: BigQuery
        type: grafana-bigquery-datasource
        access: proxy
        jsonData:
          authenticationType: gce
          defaultProject: ${PROJECT_ID}
          processingLocation: ${GCP_REGION}

plugins:
  - grafana-bigquery-datasource
